variant: cartesian
base_config: ../../task_parameters.yaml
default_stop_policy:
  min_iterations: 5000
  max_iterations: 20000
  combine: all
  criteria:
    - metric: Train/mean_episode_length
      threshold: 900.0
      mode: max
      window: 10
      patience: 10
    - metric: Episode_Termination/ball_fell_off
      threshold: 1
      mode: min
      window: 10
      patience: 10
global_overrides:
  training:
    upload_videos_to_wandb: false
  ppo:
    max_iterations: 30000
runs:
  - name: robot_model_only
    presets: [zero_ball_reset_velocity, simple_rewards, robot_model_only]
    overrides: {}
