training:
  use_observation_noise: false
  randomize_ball_reset: false
  randomize_ball_properties: true
  randomize_pd_gains: false
  randomize_robot_model: false
  randomize_null_space_init: false
  use_ball_kick: false
