rewards:
  is_alive: 1.0
  ball_no_contact: -20.0
  plate_drop_under_ball: 0.0
  racquet_centering: 20.0

  action_rate_l2: 5.0
  action_acc_l2: 0.0
  joint_vel_l2: 0.0
  joint_acc_l2: 0.0
  joint_torque_l2: 0.0
  joint_pos_limits: 0.0
  racquet_lin_vel_l2: -50.0
  racquet_ang_vel_l2: -50.0
  racquet_orientation_centering: 0.0
