variant: cartesian
base_config: ../task_parameters.yaml
default_stop_policy:
  min_iterations: 5000
  max_iterations: 20000
  combine: all
  criteria:
    - metric: Train/mean_episode_length
      threshold: 900.0
      mode: max
      window: 10
      patience: 10
    - metric: Episode_Termination/ball_fell_off
      threshold: 1
      mode: min
      window: 10
      patience: 10
global_overrides:
  cartesian_action:
    delta_pos_scale: 0.05
    delta_ori_scale: 0.5
  ppo:
    max_iterations: 30000
runs:
  - name: no_rand
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        no_rand,
      ]
    overrides: {}
  - name: obs_noise_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        obs_noise_only,
      ]
    overrides: {}
  - name: ball_reset_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        ball_reset_only,
      ]
    overrides: {}
  - name: ball_reset_linear_velocity_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        ball_reset_linear_velocity_only,
      ]
    overrides: {}
  - name: ball_reset_angular_velocity_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        ball_reset_angular_velocity_only,
      ]
    overrides: {}
  - name: ball_properties_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        ball_properties_only,
      ]
    overrides: {}
  - name: pd_gains_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        pd_gains_only,
      ]
    overrides: {}
  - name: robot_model_only
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        robot_model_only,
      ]
    overrides: {}
  - name: ball_properties_and_racquet_model
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        ball_properties_only,
        racquet_model_only,
      ]
    overrides: {}
  - name: no_model_rand
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        no_model_rand,
      ]
    overrides: {}
  - name: all_except_robot_model
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        all_except_robot_model,
      ]
    overrides: {}
  - name: all_randomization
    presets:
      [
        zero_ball_reset_velocity,
        simple_rewards,
        all_randomization,
      ]
    overrides: {}
