from __future__ import annotations

import argparse
import json
from dataclasses import asdict
from pathlib import Path
from typing import Any

import torch

import mjlab.tasks  # noqa: F401
import mjlab_kinova  # noqa: F401
from mjlab.envs import ManagerBasedRlEnv
from mjlab.rl import MjlabOnPolicyRunner, RslRlVecEnvWrapper
from mjlab.tasks.registry import load_runner_cls
from mjlab_kinova.tasks import ball_balancing_mdp as bb_mdp
from mjlab_kinova.tasks.kinova_ball_balancing_env_cfg import (
    kinova_ball_balancing_env_cfg,
    kinova_ppo_runner_cfg,
)
from mjlab_kinova.train_set import (
    TASK_ID_BY_VARIANT,
    _base_parameters,
    _build_run_parameters,
    _load_training_set,
    _normalize_run,
    _resolve_run_cfg,
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Debug actor observations for a Kinova policy checkpoint by printing "
            "the raw actor vector, the normalized actor vector, the per-term split, "
            "and the policy action."
        )
    )
    parser.add_argument(
        "training_set",
        help="Path to the training-set YAML used to resolve the run parameters.",
    )
    parser.add_argument(
        "--run",
        required=True,
        dest="run_name",
        help="Run name inside the training set (for example all_randomization_no_joint_pos).",
    )
    parser.add_argument(
        "--checkpoint-file",
        required=True,
        help="Path to the local .pt checkpoint file to inspect.",
    )
    parser.add_argument(
        "--steps",
        type=int,
        default=1,
        help="Number of environment steps to print. Default: 1.",
    )
    parser.add_argument(
        "--device",
        default=None,
        help="Torch device to use. Default: cuda:0 if available, else cpu.",
    )
    parser.add_argument(
        "--json-out",
        default=None,
        help="Optional path to dump the collected debug data as JSON.",
    )
    parser.add_argument(
        "--real-obs-json",
        default=None,
        help=(
            "Optional JSON file containing real-robot actor observations to compare against the checkpoint. "
            "Accepted formats: raw actor_obs vector, actor_terms mapping, or a full dump generated by this script."
        ),
    )
    parser.add_argument(
        "--real-obs-step",
        type=int,
        default=0,
        help="Step index to read when --real-obs-json points to a multi-record dump. Default: 0.",
    )
    parser.add_argument(
        "--precision",
        type=int,
        default=6,
        help="Number of decimals to print. Default: 6.",
    )
    return parser.parse_args()


def _resolve_run_params(training_set_path: Path, run_name: str):
    training_set_cfg = _load_training_set(training_set_path)
    base_params = _base_parameters(training_set_cfg, training_set_path=training_set_path)

    matched: tuple[list[str], dict[str, Any]] | None = None
    for index, raw_run_cfg in enumerate(training_set_cfg["runs"]):
        raw_run_cfg = _resolve_run_cfg(
            raw_run_cfg,
            index=index,
            relative_to=training_set_path.parent,
        )
        candidate_name, preset_refs, overrides = _normalize_run(raw_run_cfg, index=index)
        if candidate_name == run_name:
            matched = (preset_refs, overrides)
            break

    if matched is None:
        raise ValueError(f"Run `{run_name}` was not found in {training_set_path}")

    preset_refs, overrides = matched
    params = _build_run_parameters(
        run_name=run_name,
        preset_refs=preset_refs,
        overrides=overrides,
        training_set_path=training_set_path,
        base_params=base_params,
    )
    return training_set_cfg, params


def _actor_term_debug_payload(env: ManagerBasedRlEnv) -> list[dict[str, Any]]:
    manager = env.observation_manager
    actor_terms = manager.active_terms["actor"]
    actor_dims = manager._group_obs_term_dim["actor"]
    actor_cfgs = manager._group_obs_term_cfgs["actor"]
    obs_entries = dict(manager.get_active_iterable_terms(0))

    payload: list[dict[str, Any]] = []
    for name, dims, cfg in zip(actor_terms, actor_dims, actor_cfgs, strict=False):
        key = f"actor-{name}"
        flat = torch.tensor(obs_entries[key], dtype=torch.float32)
        entry: dict[str, Any] = {
            "name": name,
            "flat_shape": list(dims),
            "flat": flat.tolist(),
        }
        if cfg.history_length > 0 and cfg.flatten_history_dim:
            per_timestep_dim = int(flat.numel() // cfg.history_length)
            entry["history_length"] = int(cfg.history_length)
            entry["history"] = (
                flat.view(cfg.history_length, per_timestep_dim).tolist()
            )
        payload.append(entry)
    return payload



def _ee_ft_debug_payload(env: ManagerBasedRlEnv) -> dict[str, Any]:
    force_sensor = env.scene["robot/EEForceSensor_fsensor"]
    torque_sensor = env.scene["robot/EEForceSensor_tsensor"]
    raw_wrench = torch.cat((force_sensor.data, torque_sensor.data), dim=-1)
    bias = getattr(env, "_ee_ft_bias", torch.zeros_like(raw_wrench))
    debiased_wrench = raw_wrench - bias
    ball_contact_state = bb_mdp.ball_contact_state_mujoco(env)[0]
    bias_pending = getattr(env, "_ee_ft_bias_pending", None)
    robot = env.scene["robot"]
    return {
        "raw_wrench": raw_wrench[0].detach().cpu().tolist(),
        "stored_bias": bias[0].detach().cpu().tolist(),
        "debiased_wrench": debiased_wrench[0].detach().cpu().tolist(),
        "ball_contact_state": ball_contact_state.detach().cpu().tolist(),
        "bias_pending": None if bias_pending is None else bool(bias_pending[0].item()),
        "joint_pos": robot.data.joint_pos[0].detach().cpu().tolist(),
        "joint_vel": robot.data.joint_vel[0].detach().cpu().tolist(),
    }


def _print_ee_ft_debug_payload(payload: dict[str, Any]) -> None:
    print("robot/joint_pos")
    print(torch.tensor(payload["joint_pos"]))
    print()
    print("robot/joint_vel")
    print(torch.tensor(payload["joint_vel"]))
    print()
    print(f"ee_ft/bias_pending={payload['bias_pending']}")
    print()
    print("ee_ft/raw_wrench")
    print(torch.tensor(payload["raw_wrench"]))
    print()
    print("ee_ft/stored_bias")
    print(torch.tensor(payload["stored_bias"]))
    print()
    print("ee_ft/debiased_wrench")
    print(torch.tensor(payload["debiased_wrench"]))
    print()
    print("ball_contact_state")
    print(torch.tensor(payload["ball_contact_state"]))
    print()

def _print_term_payload(term_payload: list[dict[str, Any]], precision: int) -> None:
    for entry in term_payload:
        name = entry["name"]
        flat_shape = tuple(entry["flat_shape"])
        print(f"actor/{name} shape={flat_shape}")
        if "history" in entry:
            history = torch.tensor(entry["history"])
            print(history)
        else:
            values = torch.tensor(entry["flat"])
            print(values)
        print()



def _flatten_real_term_payload(term_payload: list[dict[str, Any]], actor_term_order: list[str]) -> list[float]:
    terms_by_name = {entry["name"]: entry for entry in term_payload}
    flattened: list[float] = []
    for name in actor_term_order:
        if name not in terms_by_name:
            raise KeyError(f"Missing actor term `{name}` in real observation payload")
        flattened.extend(terms_by_name[name]["flat"])
    return flattened


def _flatten_term_mapping(term_mapping: dict[str, Any], actor_term_order: list[str]) -> list[float]:
    flattened: list[float] = []
    for name in actor_term_order:
        if name not in term_mapping:
            raise KeyError(f"Missing actor term `{name}` in real observation mapping")
        value = term_mapping[name]
        tensor = torch.tensor(value, dtype=torch.float32)
        flattened.extend(tensor.reshape(-1).tolist())
    return flattened


def _load_real_actor_obs(json_path: Path, actor_term_order: list[str], step: int) -> torch.Tensor:
    payload = json.loads(json_path.read_text(encoding="utf-8"))

    if isinstance(payload, dict) and "records" in payload:
        records = payload["records"]
        if not isinstance(records, list) or not records:
            raise ValueError(f"`records` in {json_path} must be a non-empty list")
        if step < 0 or step >= len(records):
            raise IndexError(f"Requested real observation step {step} but only {len(records)} records are available")
        record = records[step]
        if "actor_obs" in record:
            return torch.tensor(record["actor_obs"], dtype=torch.float32).unsqueeze(0)
        if "actor_terms" in record:
            flat = _flatten_real_term_payload(record["actor_terms"], actor_term_order)
            return torch.tensor(flat, dtype=torch.float32).unsqueeze(0)
        raise ValueError(f"Record {step} in {json_path} does not contain `actor_obs` or `actor_terms`")

    if isinstance(payload, dict) and "actor_obs" in payload:
        return torch.tensor(payload["actor_obs"], dtype=torch.float32).unsqueeze(0)

    if isinstance(payload, dict) and "actor_terms" in payload:
        actor_terms = payload["actor_terms"]
        if isinstance(actor_terms, list):
            flat = _flatten_real_term_payload(actor_terms, actor_term_order)
        elif isinstance(actor_terms, dict):
            flat = _flatten_term_mapping(actor_terms, actor_term_order)
        else:
            raise TypeError("`actor_terms` must be a list or mapping")
        return torch.tensor(flat, dtype=torch.float32).unsqueeze(0)

    if isinstance(payload, dict) and all(name in payload for name in actor_term_order):
        flat = _flatten_term_mapping(payload, actor_term_order)
        return torch.tensor(flat, dtype=torch.float32).unsqueeze(0)

    if isinstance(payload, list):
        return torch.tensor(payload, dtype=torch.float32).unsqueeze(0)

    raise ValueError(
        f"Unsupported real observation JSON format in {json_path}. "
        "Expected a raw vector, actor_terms mapping, or a dump generated by this script."
    )


def _compare_and_print_real_obs(
    *,
    real_actor_obs: torch.Tensor,
    sim_actor_obs: torch.Tensor,
    sim_normalized_actor_obs: torch.Tensor,
    sim_action: torch.Tensor,
    policy,
) -> dict[str, Any]:
    with torch.no_grad():
        if hasattr(policy, "obs_normalizer"):
            real_actor_obs_normalized = policy.obs_normalizer(real_actor_obs.clone())
        else:
            real_actor_obs_normalized = real_actor_obs.clone()
        real_action = policy({"actor": real_actor_obs})

    actor_obs_abs_diff = torch.abs(real_actor_obs - sim_actor_obs)
    normalized_abs_diff = torch.abs(real_actor_obs_normalized - sim_normalized_actor_obs)
    action_abs_diff = torch.abs(real_action - sim_action)

    print("=== real-vs-sim comparison ===")
    print(f"real_actor_obs shape={tuple(real_actor_obs.shape)}")
    print(real_actor_obs[0])
    print()
    print(f"real_actor_obs_normalized shape={tuple(real_actor_obs_normalized.shape)}")
    print(real_actor_obs_normalized[0])
    print()
    print(f"real_policy_action shape={tuple(real_action.shape)}")
    print(real_action[0])
    print()
    print("abs_diff(actor_obs)")
    print(actor_obs_abs_diff[0])
    print()
    print("abs_diff(actor_obs_normalized)")
    print(normalized_abs_diff[0])
    print()
    print("abs_diff(policy_action)")
    print(action_abs_diff[0])
    print()

    return {
        "real_actor_obs": real_actor_obs[0].cpu().tolist(),
        "real_actor_obs_normalized": real_actor_obs_normalized[0].cpu().tolist(),
        "real_policy_action": real_action[0].cpu().tolist(),
        "abs_diff_actor_obs": actor_obs_abs_diff[0].cpu().tolist(),
        "abs_diff_actor_obs_normalized": normalized_abs_diff[0].cpu().tolist(),
        "abs_diff_policy_action": action_abs_diff[0].cpu().tolist(),
        "max_abs_diff_actor_obs": float(actor_obs_abs_diff.max().item()),
        "max_abs_diff_actor_obs_normalized": float(normalized_abs_diff.max().item()),
        "max_abs_diff_policy_action": float(action_abs_diff.max().item()),
    }

def main() -> int:
    args = _parse_args()
    torch.set_printoptions(precision=args.precision, sci_mode=False, linewidth=160)

    training_set_path = Path(args.training_set).resolve()
    checkpoint_path = Path(args.checkpoint_file).resolve()
    if not checkpoint_path.exists():
        raise FileNotFoundError(f"Checkpoint file not found: {checkpoint_path}")

    training_set_cfg, params = _resolve_run_params(training_set_path, args.run_name)
    variant = training_set_cfg["variant"]
    task_id = TASK_ID_BY_VARIANT[variant]
    device = args.device or ("cuda:0" if torch.cuda.is_available() else "cpu")

    print(f"[obs-debug] task_id={task_id}")
    print(f"[obs-debug] variant={variant}")
    print(f"[obs-debug] run={args.run_name}")
    print(f"[obs-debug] checkpoint={checkpoint_path}")
    print(f"[obs-debug] device={device}")
    print(f"[obs-debug] note: ee_quat uses wxyz order")

    env_cfg = kinova_ball_balancing_env_cfg(variant=variant, play=True, params=params)
    env_cfg.scene.num_envs = 1
    env = ManagerBasedRlEnv(cfg=env_cfg, device=device, render_mode=None)
    vec_env = RslRlVecEnvWrapper(env, clip_actions=1.0)

    try:
        runner_cfg = kinova_ppo_runner_cfg(variant=variant, params=params)
        runner_cls = load_runner_cls(task_id) or MjlabOnPolicyRunner
        runner = runner_cls(vec_env, asdict(runner_cfg), device=device)
        runner.load(str(checkpoint_path), load_cfg={"actor": True}, strict=True, map_location=device)
        policy = runner.get_inference_policy(device=device)

        obs_td, _ = vec_env.reset()
        records: list[dict[str, Any]] = []

        actor_term_order = env.observation_manager.active_terms["actor"]

        for step_idx in range(args.steps):
            actor_obs = obs_td["actor"].detach().clone()
            with torch.no_grad():
                if hasattr(policy, "obs_normalizer"):
                    normalized_actor_obs = policy.obs_normalizer(actor_obs.clone())
                else:
                    normalized_actor_obs = actor_obs.clone()
                action = policy(obs_td)

            term_payload = _actor_term_debug_payload(env)
            ee_ft_payload = _ee_ft_debug_payload(env)

            print(f"\n=== step {step_idx} ===")
            print(f"actor_obs shape={tuple(actor_obs.shape)}")
            print(actor_obs[0])
            print()
            print(f"actor_obs_normalized shape={tuple(normalized_actor_obs.shape)}")
            print(normalized_actor_obs[0])
            print()
            print(f"policy_action shape={tuple(action.shape)}")
            print(action[0])
            print()
            _print_ee_ft_debug_payload(ee_ft_payload)
            _print_term_payload(term_payload, precision=args.precision)

            real_comparison = None
            if args.real_obs_json is not None:
                real_actor_obs = _load_real_actor_obs(
                    Path(args.real_obs_json).resolve(),
                    actor_term_order=actor_term_order,
                    step=args.real_obs_step + step_idx,
                ).to(actor_obs.device)
                real_comparison = _compare_and_print_real_obs(
                    real_actor_obs=real_actor_obs,
                    sim_actor_obs=actor_obs,
                    sim_normalized_actor_obs=normalized_actor_obs,
                    sim_action=action,
                    policy=policy,
                )

            records.append(
                {
                    "step": step_idx,
                    "actor_obs": actor_obs[0].cpu().tolist(),
                    "actor_obs_normalized": normalized_actor_obs[0].cpu().tolist(),
                    "policy_action": action[0].cpu().tolist(),
                    "ee_ft_debug": ee_ft_payload,
                    "actor_terms": term_payload,
                    "real_comparison": real_comparison,
                }
            )

            if step_idx + 1 < args.steps:
                obs_td, _, _, _ = vec_env.step(action)

        if args.json_out is not None:
            payload = {
                "task_id": task_id,
                "variant": variant,
                "run_name": args.run_name,
                "checkpoint_file": str(checkpoint_path),
                "device": device,
                "actor_term_order": actor_term_order,
                "records": records,
            }
            json_out_path = Path(args.json_out).resolve()
            json_out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
            print(f"[obs-debug] wrote JSON dump to {json_out_path}")
    finally:
        env.close()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
